platform :ios, '7.0'
source 'https://github.com/CocoaPods/Specs.git'
pod 'React', :subspecs => [
  'Core',
  'RCTActionSheet',
  'RCTGeolocation',
  'RCTImage',
  'RCTNetwork',
  'RCTSettings',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket'
], :path => './../node_modules/react-native'
pod 'Lock-Facebook', '~> 2.2'
pod 'LockReactNative', :path => '../node_modules/react-native-lock-ios'
#pod 'Braintree', '~> 4.1'
pod 'react-native-braintree', :path => '../node_modules/react-native-braintree'